chat/urls.py
from django.urls import path, include, re_path
from . import views
app_name = 'chat'

urlpatterns = [
    #path('', views.index, name='index'),
    #path('chat/', views.c_index, name='chat'),
    re_path('^(?P<room_name>[^/]+)/(?P<usr_id>[^/]+)/$',
            views.room, name='room'),
    re_path(r'^register/$', views.register, name='register'),
    re_path(r'^user_login/$', views.user_login, name='user_login'),
]

felixora/urls.py

from django.contrib import admin
from django.urls import path, include
from chat import views
from django.conf import settings
from django.contrib.auth.views import LoginView
from django.conf.urls.static import static

urlpatterns = [
    path('chat/', include('chat.urls', namespace='chat')),
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    
    path('login/', LoginView.as_view(template_name='login.html'), name="login"),

    path('special/', views.special, name='special'),
    #path('^chat/', include('chat.urls')),
    path('logout/', views.user_logout, name='logout'),
    # path(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
    #     'document_root': settings.MEDIA_DIR}),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User

User = get_user_model()


class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)
    about = models.CharField(max_length=124, default='Hey there i am using felixora',null = False,blank=False)

    def __str__(self):
        return self.user.username


class Message(models.Model):
    author = models.ForeignKey(
        User, related_name='author_messages', on_delete=models.CASCADE)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    chatbtwn = models.TextField()

    def __str__(self):
        return self.author.username

    def last_10_messages(roomname):
        return Message.objects.filter(chatbtwn = roomname).order_by('timestamp').all()

chat/forms.py
from django import forms
from .models import UserProfileInfo
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'password', 'email')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

chat/views.py
import json
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.utils.safestring import mark_safe
from django.shortcuts import render
from .forms import UserForm, UserProfileInfoForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
import request
from django.conf import settings
from .models import UserProfileInfo
userss = User.objects.filter(is_superuser = False)
user_list = []
for i in userss:
    user_list.append(i.username)

# uuser = User.objects.get(username=request.user.username)
# print(user)


def index(request):
    # username = request.POST.get('username')
    #print(username,"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")
    return render(request, 'users/index.html', {"All_users": user_list})


@login_required
def special(request):
    return HttpResponse("You are logged in !")


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                print('found it')
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request, 'users/registration.html',
                  {'user_form': user_form,
                           'profile_form': profile_form,
                           'registered': registered})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                print(username)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(
                username, password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'users/login.html', {})


def c_index(request):
    return render(request, 'chat/index.html', {})

@login_required
def mainroom(request, usr_id):

    img_url=settings.SITE_URL
    user_obj = UserProfileInfo.objects.get(user_id=usr_id)
    if(user_obj.profile_pic):
        usr_p_url = img_url + user_obj.profile_pic.url
    else:
        usr_p_url = img_url+'/media/profile_pics/user.png'
    usr_status = user_obj.about

    userss = User.objects.filter(is_superuser = False)
    list_of_contact=[]
    for i in userss:
        user_obj = UserProfileInfo.objects.get(user_id=i.id)
        if int(i.id) != int(usr_id):
            name = i.username
            if(user_obj.profile_pic):
                contact_p_url = img_url + user_obj.profile_pic.url
            else:
                contact_p_url = img_url+'/media/profile_pics/user.png'
            contact_about = user_obj.about
            contact_detail = {
                'name':name,
                'profile_pic':contact_p_url,
                'status':contact_about,
            }
            list_of_contact.append(contact_detail)
    return render(request, 'chat/room.html', {
        'username': mark_safe(json.dumps(request.user.username)),
        'usr_img': usr_p_url,
        'usr_status':usr_status,
        'contact_list':list_of_contact,
    })





@login_required
def room(request, room_name, usr_id):
    img_url=settings.SITE_URL
   
    reciver_id_obj = User.objects.get(username=room_name)
    reciever_id = reciver_id_obj.id
    ar = []
    ar.append(str(reciever_id))
    ar.append(str(usr_id))
    ar.sort()    
    room_id = "^".join(ar)
    
    user_obj = UserProfileInfo.objects.get(user_id=usr_id)
    if(user_obj.profile_pic):
        usr_p_url = img_url + user_obj.profile_pic.url
    else:
        usr_p_url = img_url+'/media/profile_pics/user.png'
    usr_status = user_obj.about
    
    rec_obj = UserProfileInfo.objects.get(user_id=reciever_id)
    if(rec_obj.profile_pic):
        rec_p_url = img_url + rec_obj.profile_pic.url
    else:
        rec_p_url = img_url+'/media/profile_pics/user.png'
    rec_status =rec_obj.about
    userss = User.objects.filter(is_superuser = False)
    list_of_contact=[]
    for i in userss:
        user_obj = UserProfileInfo.objects.get(user_id=i.id)
        if int(i.id) != int(usr_id):
            name = i.username
            print(name)
            if(user_obj.profile_pic):
                contact_p_url = img_url + user_obj.profile_pic.url
            else:
                contact_p_url = img_url+'/media/profile_pics/user.png'
            contact_about = user_obj.about
            contact_detail = {
                'name':name,
                'profile_pic':contact_p_url,
                'status':contact_about,
            }
            list_of_contact.append(contact_detail)
    print(list_of_contact)
    return render(request, 'chat/roomContent.html', {
        'room_name_json': room_id,
        'room_id': room_id,
        'username': mark_safe(json.dumps(request.user.username)),
        'usr_img': usr_p_url,
        'usr_status':usr_status,
        'rec_img': rec_p_url,
        'rec_status':rec_status,
        'rec_name': room_name,
        'contact_list':list_of_contact,
    })
# from django.utils.crypto import get_random_string
# chars = 'abcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*(-_=+)'
# SECRET_KEY = get_random_string(50, chars)
# print (SECRET_KEY)

chat/templates/users/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
{# Django Home Link / Admin Link / Register Link#}
          <li><a class="navbar-brand" href="{% url 'index' %}">Felixora</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'chat:register' %}">Register</a></li>     
          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'chat:user_login' %}">Login</a></li>
          {% endif %}
</ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

chat/templates/users/index.html
{% extends "users/base.html" %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    <h1>Felixora a Chat Service !</h1>
    <script> 
    var usr_id = {{ user.id }};
    //window.location.pathname = '/chat/' + dname + '/'+ usr_id +'/';
    </script>
    {% if user.is_authenticated %}
        <h2>Hello {{ user.username }}</h2>
        <body>
    List of all Users are:- 
    {%for i in All_users%}
    {% if i != user.username %}
    <li>
        
    <a class = "roomsel" href="#" data-name="{{i}}" >{{i}}</a>
    </li>
    {% endif %}
    {% endfor %}

    <script>
        $(document).on('click', '.roomsel', function(){
            var dname = $(this).attr('data-name');
            //console.log(dname);
            var usr_id = {{ user.id }};
            window.location.pathname = '/chat/' + dname + '/'+ usr_id +'/';
        })
    </script>
</body>
    {% else %}
        <h2>Register or Login if you'd like to</h2>
    {% endif %}
  </div>
</div>
{% endblock %}

chat/templates/users/login.html
{% extends 'users/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Login here :</h1>
<form method="post" action="{% url 'chat:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">
<label for="password">Password:</label>
          <input type="password" name="password" placeholder="Password">
<input type="submit" name="" value="Login">
</form>
</div>
  </div>
{% endblock %}

chat/templates/users/registration.html
{% extends "users/base.html" %}
{% load staticfiles %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>
<form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>
        
      {% endif %}
    </div>
  </div>
{% endblock %}